package allTemps

type Environment struct {
	// Program parameters:
	PointsPerSide int // length of one side of the lattice

	// Constant physical parameters:
	X   float64 // average density of holons
	T0  float64 // nn one-holon hopping energy
	Thp float64 // direct nnn one-holon hopping energy

	// Dynamically determined physical parameters:
	D1   float64 // nnn hopping parameter generated by two-holon hopping
	Mu_h float64 // holon chemical potential

	// Cached values:
	epsilonMin       float64
	lastEpsilonMinD1 float64
}

func (env *Environment) Th() float64 {
	return env.T0 * (1.0 - env.X)
}

func (env *Environment) EpsilonMin() float64 {
	if env.D1 != env.lastEpsilonMinD1 {
		env.epsilonMin = EpsilonMin(env)
		env.lastEpsilonMinD1 = env.D1
	}
	return env.epsilonMin
}
