#!/bin/bash

# brace wrapping to suppress output
# http://stackoverflow.com/questions/5960567/suppress-the-output-to-screen-in-shell-script
{
rm plots/deleteme*
rm tempAll/deleteme*
rm tempZero/deleteme*
rm tempZero/plot_data*
rm tempPair/deleteme*
rm tempPair/plot_data*
rm tempCrit/deleteme*
rm tempCrit/plot_data*
rm tempFluc/deleteme*
rm tempFluc/plot_data*
rm tempLow/plot_data*
rm scExplorer
} >/dev/null 2>&1
