#!/bin/bash

# brace wrapping to suppress output
# http://stackoverflow.com/questions/5960567/suppress-the-output-to-screen-in-shell-script
{
rm plots/deleteme*
rm tempZero/deleteme*
rm tempPair/deleteme*
} >/dev/null 2>&1
