#!/bin/bash

cd vector && go test && cd ..
cd bzone && go test && cd ..
cd solve && go test && cd ..
cd integrate && go test && cd ..
cd fit && go test && cd ..
cd serialize && go test && cd ..
cd plots && go test && cd ..
cd tempAll && go test && cd ..
cd tempZero && go test && cd ..
cd tempPair && go test && cd ..
cd tempCrit && go test && cd ..

./clean
